infer_dataset_top_directory: "/home/ssd_dir/flight_airsim_image/new_sequence1"
csv_name: "data_list.csv"

weights_top_directory: "/home/ssd_dir/rnn_attitude_estimator_log/rnn_train_2022_05_04"
weights_file_name: "weights.pth"

infer_log_top_directory: "/home/ssd_dir/rnn_attitude_estimator_log/rnn_train_2022_05_03/infer_log"
infer_log_file_name: "frame_infer_relust_building99.csv"

index_dict_name: "index_dict_-30_30_range_step1deg.csv"

resize: 224
mean_element: 0.5
std_element: 0.5
dim_fc_out: 63
enable_dropout: False
dropout_rate: 0.1
timesteps: 8